version: '3.9'

services:
  db:
    image: postgres:14
    container_name: db
    env_file:
      - stack.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure

  app-migrate:
    image: ghcr.io/aikenahac/frivsspr:master
    container_name: app-migrate
    env_file:
      - stack.env
    depends_on:
      - db
    command: ["npx", "prisma", "migrate", "deploy"]

  app-init:
    image: ghcr.io/aikenahac/frivsspr:master
    container_name: app-init
    env_file:
      - stack.env
    depends_on:
      - app-migrate
    command: ["node", "--loader", "tsx/esm", "src/seed.ts"]

  app:
    image: ghcr.io/aikenahac/frivsspr:master
    container_name: app
    env_file:
      - stack.env
    depends_on:
      - app-migrate
      - app-init
    ports:
      - 3000:3000
      - 5555:5555
    restart: on-failure

  app-beta:
    image: ghcr.io/aikenahac/frivsspr:master
    container_name: app-beta
    env_file:
      - stack.env
    depends_on:
      - app-migrate
      - app-init
    ports:
      - 3006:3000
    restart: on-failure

volumes:
  db_data:
