version: '3.9'

services:
  db:
    image: postgres:14
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
  app-migrate:
    image: frivsspr
    container_name: app-migrate
    env_file:
      - .env
    command: prisma migrate deploy
  app-init:
    image: frivsspr
    container_name: app-init
    env_file:
      - .env
    command: npx tsx src/init.ts
  app:
    image: frivsspr
    container_name: app
    env_file:
      - .env
    depends_on:
      - app-migrate
      - app-init
    ports:
      - 3000:3000
    restart: on-failure

volumes:
  db_data:
