version: '3.9'

services:
  db:
    image: postgres:14
    container_name: frivsspr_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - frivsspr_db_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  frivsspr_db_data:
